### ISSUE TITLE
Error: node_redis: The SETEX command contains a invalid argument type.

### ISSUE THREAD

**Issue by RosiersRobin** [Floydan/plex-discord-webhook#1]
Hi,

I tried the package, but I get the following;

```
Error: node_redis: The SETEX command contains a invalid argument type.
Only strings, dates and buffers are accepted. Please update your code to use valid argument types.
```

Setup everyting OKAY, however when I dump the payload, then I see the ars to be `args: [ 'ca0be3e36dd7023c637491506a51113243c72400', 604800, null ]`, the null is the `buffer` on line 130

**Comment by Floydan** [comment]
Hi, sorry for the late reply!
I'll take a look and see what I can do but this might be a change on the Plex side of things as this was built against an older version of Plex than what you probably are using

**Comment by Floydan** [comment]
@RosiersRobin 
I didn't mean to close the issue before you have had time to test it.
But if you pull the latest version from master you will have something to test

**Comment by Floydan** [comment]
@RosiersRobin as I haven't heard from you i'm closing this issue, please open a new one if you are still experiencing issues.
